### ISSUE TITLE
Add a nonValues check for Validator

### ISSUE THREAD

**Issue by Snaggybore** [FlyingKumquat/FKSrepack#16]
Add a check for the Validator to make sure the input does not exist in a passed list of values.

Since we have "values" and "values_csv" we should make two versions of them, "no_values" and "no_values_csv" or something like that.

**Comment by Snaggybore** [comment]
When this has been implemented accountRegister in the main functions.php page should be changed so that the username can be validated against protected usernames.

**Comment by FlyingKumquat** [comment]
Added in next release
