### ISSUE TITLE
Add a site setting for a default page

### ISSUE THREAD

**Issue by Snaggybore** [FlyingKumquat/FKSrepack#22]
Right now the site assumes that home is the default page and will always attempt to go there first if no page is supplied. There should be an option for changing what the default (home) page is.

**Comment by FlyingKumquat** [comment]
We got it working on the admin/settings page, still need to add it to access groups and member settings.

**Comment by Snaggybore** [comment]
Site setting is done but still need per member setting.

**Comment by Snaggybore** [comment]
Access groups should also have default page setting and follow hierarchy if multiple groups.
